version: "3.1"

networks:
  web:
    external: true

services:
  save:
    build: .
    container_name: save
    restart: always
    environment:
      - SERVER_PORT=3333
      - DEBUG=false
      - NODE_ENV=production
      - MONGO_DB=wbag
      - MONGO_ADDRS=mongodb:27017
    volumes:
      - ./cache:/app/public/cache
    labels:
      - "traefik.backend=save"
      - "traefik.domain=kumpf.io"
      - "traefik.frontend.rule=Host:save.kumpf.io"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.docker.network=web"
      - "traefik.port=3333"
    networks:
      - web
